packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  sharp: true
  unrs-resolver: true
  msw: true
  esbuild: true

catalog:
  "typescript": "^6"
  "@orpc/server": "^1.14.6"
  "@orpc/client": "^1.14.6"
  "dotenv": "^17.4.2"
  "better-auth": "^1.6.23"
  "drizzle-orm": "1.0.0-rc.4"
  "zod": "^4.4.3"
  "@neondatabase/serverless": "^1.1.0"
  "tsdown": "^0.22.3"
  "drizzle-kit": "1.0.0-rc.4"
  "tsx": "^4.23.0"
  "lucide-react": "^1.23.0"
  "next-themes": "^0.4.6"
  "react": "19.2.4"
  "react-dom": "19.2.4"
  "@tailwindcss/postcss": "^4"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "eslint": "^9"
  "hono": "^4.12.27"
  "@types/node": "^20.19.41"
